http:
  services:
    whoami:
      loadBalancer:
        servers:
          - url: http://whoami:80

  middlewares:
    oidc-auth:
      plugin:
        traefik-oidc-auth:
          logLevel: DEBUG
          secret: "0123456789abcdef0123456789abcdef" # Please change this secret for your setup
          provider:
            url: "${PROVIDER_URL}"
            clientId: "${CLIENT_ID}"
            clientSecret: "${CLIENT_SECRET}"
            usePkce: true
            validateAudience: "${VALIDATE_AUDIENCE}"
          scopes: ["openid", "profile", "email"]
          headers:
            - name: "X-Oidc-Username"
              value: "{{`{{ .claims.preferred_username }}`}}"
            - name: "X-Oidc-Subject"
              value: "sub"
            - name: "Authorization"
              value: "{{`Bearer {{ .accessToken }}`}}"
              # IncludeWhen: "Public"
            - name: "IdToken"
              value: "{{`Bearer {{ .idToken }}`}}"
          authorizationHeader:
            name: "CustomAuth"
          authorizationCookie:
            name: "CustomAuth"
          #bypassAuthenticationRule: "Header(`cache-control`, `no-cache`) || HeaderRegexp(`X-Real-Ip`, `^172\\.18\\.`)"
          #unauthorizedBehavior: "Unauthorized"
          #authorizationParams:
          #  acr_values: "aal2"
          #  prompt: "login"
          # authorization:
          #   assertClaims:
          #     - Name: roles
          #       anyOf: ["admin", "media"]
          #     - Name: some.nested.key
          #       anyOf: ["some value"]
          # If set, only the /login endpoint will initiate the login flow
          loginUri: "/login"
          #ValidPostLoginRedirectUris: ["https://google.at"]
          #ValidPostLogoutRedirectUris: ["https://google.at"]
          #PostLoginRedirectUri: "/"

  routers:
    whoami:
      entryPoints: ["web"]
      rule: "HostRegexp(`.+`)"
      service: whoami
      middlewares: ["oidc-auth@file"]
