name: Backport

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers] no PR code is checked out; only used to create backport PRs via API
    types: ["labeled", "closed"]

permissions: {}

concurrency:
  group: backport-${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  backport:
    name: Backport PR
    permissions:
      contents: write # so it can comment
      pull-requests: write # so it can create pull requests
    if: >
      github.event.pull_request.merged &&
      (
        (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'backport')) ||
        (github.event.action == 'labeled' && contains(github.event.label.name, 'backport'))
      )
    runs-on: ubuntu-latest
    steps:
      - name: Backport Action
        uses: sorenlouv/backport-github-action@8a6c0381851f43f9f1fddc7303f0e9015eb57b62 # v12.0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          auto_backport_label_prefix: backport/

      - name: Info log
        if: ${{ success() }}
        run: cat ~/.backport/backport.info.log
        
      - name: Debug log
        if: ${{ failure() }}
        run: cat ~/.backport/backport.debug.log        
          