name: Run Go tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "website/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install dependencies
        working-directory: ./src
        run: go get .

      - name: Build
        working-directory: ./src
        run: go build

      - name: Test with the Go CLI
        working-directory: ./src
        run: go test

      - name: Build extauth-server
        working-directory: ./cmd/extauth-server
        run: go build

      - name: Test extauth-server
        working-directory: ./cmd/extauth-server
        run: go test
